# Generated by Django 5.2.7 on 2025-11-21 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_published_post_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название идеи')),
                ('description', models.TextField(verbose_name='Описание идеи')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('proposed', 'Предложена'), ('under_review', 'На рассмотрении'), ('accepted', 'Принята'), ('rejected', 'Отклонена'), ('implemented', 'Реализована')], default='proposed', max_length=15, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Комментарии администратора')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Идея',
                'verbose_name_plural': 'Идеи',
                'ordering': ['-created'],
            },
        ),
    ]
