# Generated by Django 5.2.7 on 2025-11-22 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_idea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('page_views', models.IntegerField(default=0, verbose_name='Просмотры страниц')),
                ('unique_visitors', models.IntegerField(default=0, verbose_name='Уникальные посетители')),
                ('new_users', models.IntegerField(default=0, verbose_name='Новые пользователи')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доход')),
            ],
            options={
                'verbose_name': 'Аналитика',
                'verbose_name_plural': 'Аналитика',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#FF00FF', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Показать на главной'),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='idea',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Бюджет'),
        ),
        migrations.AddField(
            model_name='idea',
            name='estimated_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка времени (дни)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='priority',
            field=models.CharField(choices=[('low', '🟢 Низкий'), ('medium', '🟡 Средний'), ('high', '🟠 Высокий'), ('critical', '🔴 Критический')], default='medium', max_length=10, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='idea',
            name='tags',
            field=models.CharField(blank=True, max_length=200, verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='idea',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='Голоса'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемая'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='post',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', max_length=10, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='post',
            name='reading_time',
            field=models.IntegerField(default=5, verbose_name='Время чтения (мин)'),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_description',
            field=models.TextField(blank=True, max_length=300, verbose_name='SEO описание'),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='SEO заголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
