# Generated by Django 5.2.7 on 2025-11-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_analytics_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analytics',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='estimated_time',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reading_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
    ]
